services:
  - type: web
    name: my-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -t my-backend .
    startCommand: docker run -p 5000:5000 my-backend